Upload the test results as artifact for now

diff --git a/.github/workflows/build-and-test.yaml b/.github/workflows/build-and-test.yaml
--- a/.github/workflows/build-and-test.yaml
+++ b/.github/workflows/build-and-test.yaml
@@ -53,27 +53,43 @@ jobs:
           -configuration Debug \
           -destination "$DEST" \
           -derivedDataPath DerivedData \
-          -enableCodeCoverage YES \
-          -resultBundlePath TestResults 
+          -enableCodeCoverage YES
           
-      # Install xcresultparser (from Homebrew)
-      - name: Install xcresultparser
+      # Force stop test host
+      - name: Force stop test host (avoid hangs)
+        if: failure() || success()  # always run
         run: |
-          brew install a7ex/tap/xcresultparser
+          killall -9 PingTestHost 2>/dev/null || true
 
-      # Parse and generate JUnit results
-      - name: Convert xcresult to JUnit
-        run: |
-          xcresultparser -o junit TestResults.xcresult > TestResults.xml
-
-      # Publish JUnit test report to GitHub summary
-      - name: Publish test results to GitHub summary
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
+      # Upload .xcresult bundle
+      - name: Upload .xcresult bundle as artifact
+        uses: actions/upload-artifact@v4
+        if: always()            # Upload even if build/test fails
         with:
-          name: Tests Results
-          path: TestResults.xml
-          reporter: java-junit
+          name: TestResults
+          path: TestResults.xcresult
+          
+      # # Install xcresultparser
+      # - name: Install xcresultparser
+      #   run: |
+      #     curl -L https://github.com/a7ex/xcresultparser/releases/latest/download/xcresultparser-macos-arm64.zip -o parser.zip
+      #     unzip parser.zip -d xcparser
+      #     sudo mv xcparser/xcresultparser /usr/local/bin/xcresultparser
+      #     sudo chmod +x /usr/local/bin/xcresultparser
+
+      # # Parse and generate JUnit results
+      # - name: Convert xcresult to JUnit
+      #   run: |
+      #     xcresultparser -o junit TestResults.xcresult > TestResults.xml
+
+      # # Publish JUnit test report to GitHub summary
+      # - name: Publish test results to GitHub summary
+      #   uses: dorny/test-reporter@v1
+      #   if: success() || failure()
+      #   with:
+      #     name: Tests Results
+      #     path: TestResults.xml
+      #     reporter: java-junit
 
       # # Publish test results
       # - name: Publish test results
